name: Example CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - uses: actions/checkout@v4

      # 2. Node.js 버전 설정 및 npm 캐싱
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      # 3. Lock 파일 존재 여부 확인
      - name: Check for lock file
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Error: package-lock.json is missing."
            exit 1
          fi

      # 4. 의존성 설치 (lock 파일 기반)
      - name: Install dependencies
        run: |
          npm ci || npm install

      # 5. 테스트 실행
      - name: Run tests
        run: npm test

      # 6. 빌드 (선택 사항: 빌드 단계가 필요한 경우 추가)
      - name: Build project
        run: npm run build
